[nixpacks]
  nodeVersion = "20"
  pkgs = ["nodejs-20_x"]

[build]
  installCommand = "npm install --legacy-peer-deps"
  buildCommand = "npm run build"

[deploy]
  startCommand = "npx serve dist -s -l 3000"